import os


SENDER = os.getenv('SENDER', None)
TEST_RECIPIENT = os.getenv('TEST_RECIPIENT', None)

GROUPS_SPREADSHEET = os.getenv('GROUPS_SPREADSHEET', None)
USERS_SPREADSHEET = os.getenv('USERS_SPREADSHEET', None)